import { GoogleGenAI } from "@google/genai";
import { GEMINI_API_KEY, GEMINI_MODEL } from "./envConfig.js";

const apiKey = GEMINI_API_KEY || process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.warn(" Warning: GEMINI_API_KEY is not set in environment variables. Gemini API requests will fail until key is configured.");
}

/**
 * Initialized Google Gen AI SDK client instance
 */
export const ai = new GoogleGenAI({
  apiKey: apiKey || "",
});

/**
 * List of available free-tier Gemini Flash models:
 * - gemini-2.5-flash: Flagship fast & intelligent multimodal model (Recommended)
 * - gemini-2.0-flash: Next-gen high speed multimodal model
 * - gemini-2.0-flash-lite: Cost-effective ultra-fast model
 * - gemini-1.5-flash: High speed, low latency multimodal model
 * - gemini-1.5-flash-8b: Lightweight model for high-frequency text tasks
 */
export const GEMINI_FLASH_MODELS = {
  GEMINI_3_6_FLASH: "gemini-3.6-flash",
  GEMINI_3_5_FLASH: "gemini-3.5-flash",
  GEMINI_3_5_FLASH_LITE: "gemini-3.5-flash-lite",
  GEMINI_3_8_FLASH: "gemini-3.8-flash",
  GEMINI_3_7_FLASH: "gemini-3.7-flash",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

/**
 * Fallback order for Gemini models if primary model is unavailable or rate-limited
 */
export const FALLBACK_MODEL_LIST = [
  GEMINI_FLASH_MODELS.GEMINI_3_6_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_5_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_5_FLASH_LITE,
  GEMINI_FLASH_MODELS.GEMINI_3_8_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_7_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_FLASH_PREVIEW,
];

/**
 * Default Gemini model used across the backend
 */
export const DEFAULT_GEMINI_MODEL = GEMINI_MODEL || GEMINI_FLASH_MODELS.GEMINI_3_6_FLASH;

/**
 * Reusable function to generate content with automatic model fallback loop.
 * If the primary model fails or is unavailable, it automatically retries with the next model.
 * 
 * @param {Object} options - Function options
 * @param {string|Array} options.contents - Prompt text string or array of parts (text/inline image data)
 * @param {string} [options.model] - Primary model name (defaults to GEMINI_2_5_FLASH)
 * @param {string} [options.systemInstruction] - System prompt instruction to guide model behavior
 * @param {Object} [options.config] - Extra generation config (temperature, maxOutputTokens, responseMimeType, etc.)
 * @returns {Promise<string>} Text output generated by Gemini
 */
export const generateGeminiContent = async ({
  contents,
  model = DEFAULT_GEMINI_MODEL,
  systemInstruction,
  config
} = {}) => {
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is missing. Please set GEMINI_API_KEY in your .env file.");
  }

  // Create an ordered, unique list of models starting with requested model
  const modelsToTry = Array.from(new Set([model, DEFAULT_GEMINI_MODEL, ...FALLBACK_MODEL_LIST])).filter(Boolean);
  const errors = [];

  for (const currentModel of modelsToTry) {
    try {
      const requestOptions = {
        model: currentModel,
        contents,
        config: {
          ...(systemInstruction ? { systemInstruction } : {}),
          ...config,
        },
      };

      const response = await ai.models.generateContent(requestOptions);
      const text = response.text;
      try {
        return JSON.parse(text);
      } catch {
        return text;
      }
    } catch (error) {
      console.warn(`⚠️ [Gemini Model ${currentModel} Failed]: ${error.message || error}. Attempting next fallback model...`);
      errors.push({ model: currentModel, error: error.message || error });
    }
  }

  // If all models in loop fail
  const errorDetails = errors.map((e) => `[${e.model}: ${e.error}]`).join(", ");
  console.error(` [Gemini Error]: All models failed. Details: ${errorDetails}`);
  throw new Error(`All Gemini Flash models failed. Attempted models: ${modelsToTry.join(", ")}`);
};

export default generateGeminiContent;
